# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Remaining workspace-scoped factories: webhooks, API tokens, exports, assets,
public boards, favourites and draft work items."""

from __future__ import annotations

from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict

from autonoma import define_factory
from plane.app.serializers import DraftIssueCreateSerializer, WebhookSerializer
from plane.db.models import (
    APIToken,
    DeployBoard,
    DraftIssue,
    ExporterHistory,
    FileAsset,
    Project,
    UserFavorite,
    Webhook,
)

from ..support import acting_user, db_call, offset_date, offset_datetime, resolve_user


class WebhookInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    workspace_id: str
    url: str
    created_by_id: Optional[str] = None
    is_active: bool = True
    project: bool = True
    issue: bool = True
    module: bool = False
    cycle: bool = False
    issue_comment: bool = False


def _webhook_create(data: WebhookInput, ctx: Any) -> dict:
    # WebhookSerializer.create runs the SSRF and disallowed-domain checks and
    # generates the signing secret; both matter for a webhook that looks real.
    actor = resolve_user(data.created_by_id)

    with acting_user(actor):
        serializer = WebhookSerializer(
            data={
                "url": data.url,
                "is_active": data.is_active,
                "project": data.project,
                "issue": data.issue,
                "module": data.module,
                "cycle": data.cycle,
                "issue_comment": data.issue_comment,
            }
        )
        serializer.is_valid(raise_exception=True)
        webhook = serializer.save(workspace_id=data.workspace_id)

    return {"id": str(webhook.id), "workspace_id": str(webhook.workspace_id), "url": webhook.url}


def _webhook_teardown(record: dict, ctx: Any) -> None:
    Webhook.all_objects.filter(pk=record["id"]).delete()


Webhook_ = define_factory(
    create=db_call(_webhook_create),
    input_model=WebhookInput,
    teardown=db_call(_webhook_teardown),
)


class APITokenInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    user_id: str
    label: Optional[str] = None
    description: str = ""
    workspace_id: Optional[str] = None
    # Offset in days: the token value itself is generated by the model, but an
    # expiry the app compares against now must be derived at seeding time.
    expires_in_days: Optional[float] = None


def _token_create(data: APITokenInput, ctx: Any) -> dict:
    # ApiTokenEndpoint.post creates the row directly; the token string and the
    # user_type come from the model, never from the recipe.
    user = resolve_user(data.user_id)

    with acting_user(user):
        token = APIToken.objects.create(
            label=data.label or str(uuid4().hex),
            description=data.description,
            user=user,
            user_type=1 if user.is_bot else 0,
            workspace_id=data.workspace_id,
            expired_at=offset_datetime(days=data.expires_in_days),
        )

    return {
        "id": str(token.id),
        "user_id": str(token.user_id),
        "workspace_id": str(token.workspace_id) if token.workspace_id else None,
        "token": token.token,
        "label": token.label,
    }


def _token_teardown(record: dict, ctx: Any) -> None:
    APIToken.all_objects.filter(pk=record["id"]).delete()


APIToken_ = define_factory(
    create=db_call(_token_create),
    input_model=APITokenInput,
    teardown=db_call(_token_teardown),
)


class ExporterHistoryInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    workspace_id: str
    initiated_by_id: str
    project_ids: list[str] = []
    provider: str = "csv"
    status: str = "completed"


def _exporter_create(data: ExporterHistoryInput, ctx: Any) -> dict:
    # ExportIssuesEndpoint.post creates the row inline and then queues the export
    # task. The insert is reproduced; the task (which writes a file to object
    # storage) is not, so the status is whatever the recipe asks for.
    user = resolve_user(data.initiated_by_id)

    with acting_user(user):
        exporter = ExporterHistory.objects.create(
            workspace_id=data.workspace_id,
            project=[str(project_id) for project_id in data.project_ids],
            initiated_by=user,
            provider=data.provider,
            type="issue_exports",
            status=data.status,
        )

    return {
        "id": str(exporter.id),
        "workspace_id": str(exporter.workspace_id),
        "initiated_by_id": str(exporter.initiated_by_id),
        "provider": exporter.provider,
    }


def _exporter_teardown(record: dict, ctx: Any) -> None:
    ExporterHistory.all_objects.filter(pk=record["id"]).delete()


ExporterHistory_ = define_factory(
    create=db_call(_exporter_create),
    input_model=ExporterHistoryInput,
    teardown=db_call(_exporter_teardown),
)


class FileAssetInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    workspace_id: Optional[str] = None
    user_id: Optional[str] = None
    project_id: Optional[str] = None
    name: str = "asset.png"
    type: str = "image/png"
    size: int = 4096
    entity_type: str = FileAsset.EntityTypeContext.WORKSPACE_LOGO
    entity_identifier: Optional[str] = None


def _asset_create(data: FileAssetInput, ctx: Any) -> dict:
    # UserAssetsV2Endpoint.post builds the row inline and then asks S3 for a
    # presigned upload URL. The insert is reproduced here; the presigned URL is an
    # external-service side effect with nothing to persist, so it is skipped and the
    # asset is left is_uploaded=False, exactly as it is before a client uploads.
    user = resolve_user(data.user_id)
    asset_key = f"{uuid4().hex}-{data.name}"

    with acting_user(user):
        asset = FileAsset.objects.create(
            attributes={"name": data.name, "type": data.type, "size": data.size},
            asset=asset_key,
            size=data.size,
            user=user,
            workspace_id=data.workspace_id,
            project_id=data.project_id,
            entity_type=data.entity_type,
            entity_identifier=data.entity_identifier,
        )

    return {
        "id": str(asset.id),
        "workspace_id": str(asset.workspace_id) if asset.workspace_id else None,
        "user_id": str(asset.user_id) if asset.user_id else None,
        "asset": asset_key,
    }


def _asset_teardown(record: dict, ctx: Any) -> None:
    FileAsset.all_objects.filter(pk=record["id"]).delete()


FileAsset_ = define_factory(
    create=db_call(_asset_create),
    input_model=FileAssetInput,
    teardown=db_call(_asset_teardown),
)


class DeployBoardInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    project_id: str
    created_by_id: Optional[str] = None
    entity_name: str = "project"
    is_comments_enabled: bool = True
    is_reactions_enabled: bool = True
    is_votes_enabled: bool = True
    view_props: Optional[dict] = None


def _board_create(data: DeployBoardInput, ctx: Any) -> dict:
    # DeployBoardViewSet.create get_or_creates on (entity_name, entity_identifier)
    # and then applies the flags. The public anchor is generated by the model.
    actor = resolve_user(data.created_by_id)

    with acting_user(actor):
        board, _ = DeployBoard.objects.get_or_create(
            entity_name=data.entity_name,
            entity_identifier=data.project_id,
            project_id=data.project_id,
        )
        board.view_props = data.view_props or {
            "list": True,
            "kanban": True,
            "calendar": True,
            "gantt": True,
            "spreadsheet": True,
        }
        board.is_comments_enabled = data.is_comments_enabled
        board.is_reactions_enabled = data.is_reactions_enabled
        board.is_votes_enabled = data.is_votes_enabled
        board.save()

    return {
        "id": str(board.id),
        "project_id": str(board.project_id),
        "workspace_id": str(board.workspace_id),
        "anchor": board.anchor,
    }


def _board_teardown(record: dict, ctx: Any) -> None:
    DeployBoard.all_objects.filter(pk=record["id"]).delete()


DeployBoard_ = define_factory(
    create=db_call(_board_create),
    input_model=DeployBoardInput,
    teardown=db_call(_board_teardown),
)


class UserFavoriteInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    user_id: str
    entity_type: str = "project"
    entity_identifier: Optional[str] = None
    project_id: Optional[str] = None
    workspace_id: Optional[str] = None
    name: Optional[str] = None


def _favorite_create(data: UserFavoriteInput, ctx: Any) -> dict:
    # ProjectFavoritesViewSet.create writes this row inline.
    user = resolve_user(data.user_id)
    workspace_id = data.workspace_id
    if workspace_id is None and data.project_id:
        workspace_id = str(Project.objects.get(pk=data.project_id).workspace_id)

    with acting_user(user):
        favorite = UserFavorite.objects.create(
            user=user,
            entity_type=data.entity_type,
            entity_identifier=data.entity_identifier or data.project_id,
            project_id=data.project_id,
            workspace_id=workspace_id,
            name=data.name,
        )

    return {
        "id": str(favorite.id),
        "user_id": str(favorite.user_id),
        "workspace_id": str(favorite.workspace_id),
        "entity_type": favorite.entity_type,
    }


def _favorite_teardown(record: dict, ctx: Any) -> None:
    UserFavorite.all_objects.filter(pk=record["id"]).delete()


UserFavorite_ = define_factory(
    create=db_call(_favorite_create),
    input_model=UserFavoriteInput,
    teardown=db_call(_favorite_teardown),
)


class DraftIssueInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    project_id: str
    name: str
    created_by_id: str
    description_html: str = "<p></p>"
    priority: str = "none"
    assignee_ids: list[str] = []
    label_ids: list[str] = []
    module_ids: list[str] = []
    cycle_id: Optional[str] = None
    starts_in_days: Optional[float] = None
    target_in_days: Optional[float] = None


def _draft_create(data: DraftIssueInput, ctx: Any) -> dict:
    # DraftIssueCreateSerializer.create fans out into DraftIssueAssignee,
    # DraftIssueLabel, DraftIssueModule and DraftIssueCycle rows.
    creator = resolve_user(data.created_by_id)
    project = Project.objects.get(pk=data.project_id)

    payload: dict[str, Any] = {
        "name": data.name,
        "priority": data.priority,
        "description_html": data.description_html,
    }
    if data.assignee_ids:
        payload["assignee_ids"] = data.assignee_ids
    if data.label_ids:
        payload["label_ids"] = data.label_ids
    if data.module_ids:
        payload["module_ids"] = data.module_ids
    if data.cycle_id:
        payload["cycle_id"] = data.cycle_id

    start_date = offset_date(data.starts_in_days)
    target_date = offset_date(data.target_in_days)
    if start_date:
        payload["start_date"] = start_date.isoformat()
    if target_date:
        payload["target_date"] = target_date.isoformat()

    with acting_user(creator):
        serializer = DraftIssueCreateSerializer(
            data=payload,
            context={
                "project_id": str(project.id),
                "workspace_id": str(project.workspace_id),
            },
        )
        serializer.is_valid(raise_exception=True)
        draft = serializer.save()

    return {
        "id": str(draft.id),
        "project_id": str(draft.project_id),
        "workspace_id": str(draft.workspace_id),
        "name": draft.name,
    }


def _draft_teardown(record: dict, ctx: Any) -> None:
    DraftIssue.all_objects.filter(pk=record["id"]).delete()


DraftIssue_ = define_factory(
    create=db_call(_draft_create),
    input_model=DraftIssueInput,
    teardown=db_call(_draft_teardown),
)
